# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lunoxas/FlyRank_AI/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

In [26]:
# Refresh / Content Opportunity Scoring - WHY?

# I am choosing Refresh / Content Opportunity Scoring for finding which webpages should be reviewed first because it is an opportunity to
# improve and make it useful for people and workers with the help of AI machine learning.
# Also my model will help to rank pages for human review.
# This lane is suitable for this dataset because it contains signals that my model can rank and compare between search_volume, impressions_90d, clicks_90d, etc.
# My model will be useful for comparing between webpages on traffics and competition between them.
# This lane is suitable for me because on previous assignments i have learned and used Refresh / Content Opportunity Scoring, and
# want to develop myself on this part of machine learning.

# reading csv file
import pandas as pd

myFile = pd.read_csv("/content/content_refresh_anonymized.csv")

# adding columns in csv file to myFile

myFile[[
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "trend_direction",
    "content_id"
]]

,search_volume,impressions_90d,clicks_90d,trend_direction,content_id
0,10.0,3803,29,down,content_304f48230142
1,90.0,15320,7,down,content_a1fb4e703a9e
2,0.0,12581,11,down,content_9aa793d4d895
3,10.0,11751,58,stable,content_331d6c4de07b
4,0.0,19140,24,down,content_d99b7a2d90ca
...,...,...,...,...,...
29995,10.0,1,0,new,content_c322796023c8
29996,0.0,761,3,down,content_526572edb3fa
29997,10.0,6336,12,down,content_38112bdd0c6e
29998,10.0,154763,340,down,content_ab26273a7e7a
29999,0.0,4234,80,stable,content_887020f20b5e

## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

In [27]:

# My model will help which websites needs improvement and rank them making humans to see if the websites are working for their purposes.
# Reviewers for the websites will see the declining websites and how they can improve them for good.
# My model doesnt guarantee to improve websites. It just helps reviewers to see the downsides and help them to see a clearer overview
# of websites.
# Wrong recommendation may cost lack of time for reviewers and miss the websties that really needs improvement.
# Although my model will use precisions and give a percentage with decimals and
# try to give correct information with the help of machine learning tools.

myFile[myFile["trend_direction"]=="down"][[

    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "trend_direction",
    "content_id"

]]

,search_volume,impressions_90d,clicks_90d,trend_direction,content_id
0,10.0,3803,29,down,content_304f48230142
1,90.0,15320,7,down,content_a1fb4e703a9e
2,0.0,12581,11,down,content_9aa793d4d895
4,0.0,19140,24,down,content_d99b7a2d90ca
5,720.0,3970,1,down,content_d4084a4bc775
...,...,...,...,...,...
29989,10.0,29760,15,down,content_e859812ce999
29994,70.0,349,3,down,content_995627a1f490
29996,0.0,761,3,down,content_526572edb3fa
29997,10.0,6336,12,down,content_38112bdd0c6e
29998,10.0,154763,340,down,content_ab26273a7e7a

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [38]:

# content_331d6c4de07b has impressions_90d = 29541 , clicks_90d = 79 which is interesting because trend_direction is down when it has high
# impressions and clicks which makes the content valuable for improving and further investigation.

# client_f369cb89fc has impressions_90d = 16 , clicks_90d = 0 which is interesting because trend_direction is up when it has low impressions and clicks.
# Even though its performance is improving it still may need improvement and further investigation.


idsList = ["content_331d6c4de07b","content_d4084a4bc775"]

for content_id in idsList:
    result = myFile[myFile["content_id"] == content_id][[
        "search_volume",
        "impressions_90d",
        "clicks_90d",
        "trend_direction",
        "content_id"
    ]]

    print(result)

   search_volume  impressions_90d  clicks_90d trend_direction  \
3           10.0            11751          58          stable

             content_id
3  content_331d6c4de07b
   search_volume  impressions_90d  clicks_90d trend_direction  \
5          720.0             3970           1            down

             content_id
5  content_d4084a4bc775

## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

In [44]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# My model helps with which websites may need improvement and further investigation based on their data and comparing heading such as
# clicks_90d, impressions_90d, etc with help of precisions. It observes websites through these headings to let know
# which patterns needs more attention.
# It doesnt clarify and claim that it can improve or investigate the website. It only helps humans to understand better which websites may need
# improvement and rank them in order for humans to see.

print(myFile[[
    "content_id",
    "clicks_90d",
    "impressions_90d",
    "search_volume",
    "trend_direction"
]].head(10))

             content_id  clicks_90d  impressions_90d  search_volume  \
0  content_304f48230142          29             3803           10.0
1  content_a1fb4e703a9e           7            15320           90.0
2  content_9aa793d4d895          11            12581            0.0
3  content_331d6c4de07b          58            11751           10.0
4  content_d99b7a2d90ca          24            19140            0.0
5  content_d4084a4bc775           1             3970          720.0
6  content_9a34b442b552           0               20            0.0
7  content_a63219c6e95a           1             1724          590.0
8  content_5e6c160719bc          29            32574            0.0
9  content_c27558df2b0c           2             1240            0.0

  trend_direction
0            down
1            down
2            down
3          stable
4            down
5            down
6            down
7          stable
8            down
9            down

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.